data_ path: "data/housing.csv"
model_output_path: "models"
checkpoints_output_path: "checkpoints"

seed: 42
train_test_split: 0.3

cv_folds: 5
random_search_iterations: 5

search:
  units_list: [13, 26, 52]
  epochs_list: [50, 100, 200]
  batch_size_list: [16, 32, 64]
  learning_rate_list: [0.001, 0.01, 0.1]
